.github/workflows/build.yml
.github/workflows/cd.yml
.github/workflows/new-version.yml
projects/zlib.net/package.yml

only runs the upload/invalidate steps if we're building a newVersion (on main) or when merging (in CD).

skip upload steps on CI

---

projects/tea.xyz/gx/cc/ld
projects/tea.xyz/gx/cc/package.yml

don't pass `-rpath` with `-r`, as they conflict

---

projects/deno.land/package.yml
projects/tea.xyz/gx/cc/ld
projects/tea.xyz/gx/cc/package.yml

Builds deno.land correctly: https://github.com/teaxyz/pantry.core/commit/6284cc585c1e162247cdc4fc5d1d5bed618dac8a/checks?check_suite_id=8999639875
(leaving that whitespace change in deno.land, because a) it doesn't need two newlines, and b) deno.land 1.27.0 needs to be built anyway)

pass through `ld` more smartly

---

projects/rust-lang.org/cargo/package.yml
projects/rust-lang.org/package.yml

+rust-lang.org/cargo

---

projects/deno.land/package.yml
scripts/build/build.ts

deno needs cargo to build

---

projects/rust-lang.org/package.yml

https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#compatibility-notes

remove deprecated (finally removed?) `rls`

---

.github/workflows/build.yml
README.md
scripts/bottle.ts
scripts/build.ts
scripts/deps.ts
scripts/fetch.ts
scripts/ls.ts
scripts/sort.ts
scripts/test.ts
scripts/utils/misc.ts

Improve README somewhat. Don’t overlay files into pantry, use `TEA_PANTRY_PATH` instead. Requires tea/cli 0.11.6 for `env` key in YAML-FM

Relax requirement to build to /opt

---

projects/mesonbuild.com/package.yml

Issue is hard-coded paths in the `venv`. This makes them relocatable.
resolves https://github.com/teaxyz/pantry.core/issues/22

fix mesonbuild.com

---

projects/tea.xyz/gx/cc/ld

This needs a robust test. What package (other than haskell.org) really stretches `ld`'s legs?
Note: `clang` might want for similar passthrough logic.
resolves https://github.com/teaxyz/pantry/issues/213

better ld detection

---

projects/npmjs.com/package.yml

which we shouldn't have been using anyway, since it was bypassing our downloaded sources. this is the correct way.

npmjs.com: upstream removed ./scripts/install

---

projects/deno.land/package.yml
projects/go.dev/package.yml
projects/nodejs.org/package.yml
projects/perl.org/package.yml
projects/python.org/package.yml
projects/ruby-lang.org/package.yml

Adds `ts`, `js`, `pl`, `py`, `rb`, `go` interpreter keys to their respective packages.

add `interprets:` key to appropriate packages

---

scripts/upload.ts

- reorder code to separate _functions_ and _main_ in 2 sections (e.g., as in [ls.ts](https://github.com/teaxyz/pantry.core/blob/05c0d227146b9e99a4f63ee40839e1b537925bc0/scripts/ls.ts#L26))
- format code to uniform style
- add `bucket` as a parameter to the `get_version` and  `put ` functions to avoid the use of global variables
This is related to https://github.com/teaxyz/pantry.core/issues/32

chore: reorder and refactor scripts/upload.ts

---

.github/workflows/build.yml
scripts/bottle.ts
scripts/upload.ts

gpg sign bottles

---

projects/freedesktop.org/pkg-config/package.yml
projects/llvm.org/package.yml

Change in llvm@15 breaks pkg-config build (and possibly others, since I found that at Gnome's gitlab): https://gitlab.gnome.org/GNOME/gimp/-/issues/8649.
I'm not sure I like this solution, but it's a bug in pkg-config not llvm, really....

llvm.org@15

---

projects/rust-lang.org/package.yml
projects/tea.xyz/gx/cc/package.yml

Right now, a number of packages don't like when tea.xyz/gx/cc brings in llvm.org^15. Since darwin is using clang-14, I think we're reasonably safe to do this for now (though a smaller range might be wiser).
Proof of concept:
Before: https://github.com/teaxyz/pantry.core/actions/runs/3682963301
After: https://github.com/teaxyz/pantry.core/actions/runs/3717714454

llvm^15 doesn't agree with several of our packages

---

.github/workflows/bottle.yml
.github/workflows/build.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/cleanup.yml
.github/workflows/new-version.yml
scripts/build-deps.ts
scripts/cache-artifacts.ts
scripts/fetch-pr-artifacts.ts

use PR build artifacts on merge

---

.github/workflows/build.yml
scripts/build.plumbing.ts
scripts/build.ts

Fixes issue where we don't install zlib to build zlib even though llvm needs it.
Doing these in steps was a cool demo of our primitives but led to issues due to install all deps up front rather than just before each build so fuck it.

Just use the full build.ts

---

.github/workflows/build.yml

we just need bigger builders for some rusty stuff. pay-per-minute, but we'll see how much it hurts. should speed up linux builds in any case.

fix deno.land=1.29.2

---

.github/workflows/build.yml
projects/deno.land/package.yml
scripts/check-core-sizes.ts

Adds `build.cores` key to `package.yml` to allow specific packages to use the larger linux build environments as required. Deno is the only (known?) package to require up-building today. IIRC.

add `build.cores` yaml key to control min-required build machine

---

projects/invisible-island.net/ncurses/package.yml

For https://github.com/teaxyz/pantry.extra/pull/110#issuecomment-1377243210. Untested on Linux but I think this should work with the different shared library names.

invisible-island.net/ncurses: add legacy symlinks

---

projects/git-scm.org/config.mak
projects/git-scm.org/package.yml

The fix works by having the relative path component count be the same between bin and libexec

fix git libexec rpaths

---

projects/git-scm.org/package.yml

Passing tests (guessing those envs provide like mac does):
```sh
docker run -it debian
root@9ce00b79bc73:/# apt-get update; apt-get -y install curl
...
root@9ce00b79bc73:/# TEA_YES=1 sh <(curl tea.xyz)
...
root@9ce00b79bc73:/# tea git clone https://github.com/teaxyz/cli
Cloning into 'cli'...
/root/.tea/git-scm.org/v2.39.0/libexec/git-remote-https: error while loading shared libraries: libexpat.so.1: cannot open shared object file: No such file or directory
root@9ce00b79bc73:/# ldd ~/.tea/git-scm.org/v2.39.0/libexec/git-remote-https
...
libexpat.so.1 => not found
```
and
```sh
otool -l ~/.tea/git-scm.org/v2/libexec/git-core/git-remote-https  | grep -C2 libexpat
cmd LC_LOAD_DYLIB
cmdsize 56
name /usr/lib/libexpat.1.dylib (offset 24)
time stamp 2 Wed Dec 31 19:00:02 1969
current version …
```

git needs libexpat

---

projects/tea.xyz/gx/cc/cc.rb
projects/tea.xyz/gx/cc/package.yml

note that we have fork bomb protection in tea/cli itself so this didn't fork bomb to fruition.
Fixes https://github.com/teaxyz/cli/issues/306

Prevent fork bombing from `cc` -> `tea` symlinks

---

projects/deno.land/package.yml
projects/deno.land/unzip_option_feature.diff

Since deno always uses the newest stable rust, it's using a feature that just went stable, but our compile still has it gated behind a feature flag. So we add that in, until our rust catches up.
resolves #131

fix newer deno.land builds

---

.github/actions/apple-signing/action.yml

See: https://github.com/denoland/deno/issues/17753
fixes https://github.com/teaxyz/pantry.core/issues/276
fixes https://github.com/teaxyz/pantry.core/issues/280
fixes https://github.com/teaxyz/pantry.core/issues/281
fixes https://github.com/teaxyz/pantry.core/issues/282
fixes https://github.com/teaxyz/pantry.core/issues/283

`deno compile` produces MachO headers that fail strict validation

---

scripts/get-platform.ts

In addition to better build times, this protects us better against issues found later by moving between platforms/machines.

use self-hosted x86-64 build machine(s)

---

.github/workflows/build.yml

this fixes the extremely rare case where a package is installed during cache setup, then a never version is unpacked over it with changes that tar cannot easily handle (see: https://github.com/teaxyz/pantry.extra/pull/435 changing a directory to a symlink).
This could have been done simply in GNU tar with `--unlink-recursive --unlink-first` but BSD tar (darwin) doesn't support `--unlink-recursive`.

better clean artifact unpacking during tests

---

projects/tea.xyz/gx/cc/package.yml

Ubuntu turns on PIC/PIE by default (since 16.04). ChatGPT thinks this might be the fix. I can affirm that it helps a number of segfault issues for different packages.
Testing, you know, needed.
PR/Issuess where this fix was the correct fix:

use PIC/PIE on linux-x86-64

---

.github/actions/setup-brewkit/action.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.gitignore
README.md
tea.yaml

Fixes https://github.com/teaxyz/cli/issues/427
We build to TEA_PREFIX by default in pantry dev-envs now. You can still override this if you want.
`TEA_PANTRY_PATH=foo tea bar` will now use

Don’t set TEA_PREFIX
