- .github/workflows/build.yml
- projects/gnu.org/coreutils/package.yml
> +gnu.org/coreutils

- projects/pip.pypa.io/package.yml
- projects/python.org/package.yml
Requires https://github.com/teaxyz/cli/pull/103 ~and the build fixes from https://github.com/teaxyz/pantry.core/pull/3~
> +pip.pypa.io

- projects/npmjs.com/package.yml
Requires https://github.com/teaxyz/cli/pull/102 ~and the build fixes in https://github.com/teaxyz/pantry.core/pull/3~
> +npmjs.com

- projects/ruby-lang.org/package.yml
- projects/rubygems.org/package.yml
resolves https://github.com/teaxyz/pantry/issues/199
> +rubygems.org

- projects/sourceware.org/bzip2/Makefile-libbz2_dylib
- projects/sourceware.org/bzip2/package.yml
resolves https://github.com/teaxyz/pantry/issues/28
> +bzip2(dylib)

- projects/curl.se/package.yml
- projects/darwinsys.com/file/package.yml
- projects/freedesktop.org/fontconfig/package.yml
- projects/freedesktop.org/shared-mime-info/package.yml
- projects/git-scm.org/package.yml
- projects/github.com/westes/flex/package.yml
- projects/gnu.org/bison/package.yml
- projects/gnu.org/fribidi/package.yml
- projects/gnu.org/gettext/package.yml
- projects/gnu.org/gperf/package.yml
- projects/harfbuzz.org/package.yml
- projects/ijg.org/package.yml
- projects/invisible-island.net/ncurses/package.yml
- projects/libexpat.github.io/package.yml
- projects/libpng.org/package.yml
- projects/mesonbuild.com/package.yml
- projects/nasm.us/package.yml
- projects/pcre.org/package.yml
- projects/sqlite.org/package.yml
- projects/stedolan.github.io/jq/package.yml
- projects/tea.xyz/gx/cc/package.yml
- projects/tukaani.org/xz/package.yml
- projects/unicode.org/package.yml
resolves: https://github.com/teaxyz/cli/issues/170
Cancelling checks since it's a lot of CPU time for nothing. We'll want to do that on merge, too.
> add `provides:` where missing

- projects/gnu.org/autoconf/package.yml
- projects/gnu.org/automake/package.yml
- projects/gnu.org/libtool/package.yml
- projects/ijg.org/package.yml
- projects/pyyaml.org/package.yml
I tested all of these with curl and they worked.
> Switch from http to https

- .github/workflows/build.yml
> don't overbottle

- .github/workflows/build.yml
- scripts/build.plumbing.ts
- scripts/build.ts
- scripts/build/build.ts
- scripts/fetch.ts
> build.ts only deps on deno

- scripts/build/build.ts
> Fix hardcoded /opt

- .github/workflows/build.yml
- scripts/bottle.ts
> fix gpg signing

- projects/deno.land/package.yml
Depends on https://github.com/teaxyz/cli/pull/207 and https://github.com/teaxyz/pantry.core/pull/43
Fixes https://github.com/teaxyz/pantry.core/issues/26
> deno: disable update check

- .github/workflows/build.yml
- projects/go.dev/package.yml
This appears to work. Now... how to _really_ test it?
@mxcl, somewhere we seem to have broken fix-elf.ts: [log](https://github.com/teaxyz/pantry.core/actions/runs/3492610073/jobs/5846572338). It was last seen working in the wild rubygems rebuilt using tea@0.13.0 and pantry.core 99253c44678bd7329ec5dcd08e4d471ed42abdc6
resolves #21
> codesigning

- .github/workflows/build.yml
- scripts/bottle.ts
- scripts/upload.ts
> separate upload logic from bottling logic

- projects/tea.xyz/gx/cc/cc.rb
- projects/tea.xyz/gx/cc/package.yml
- scripts/brewkit/fix-machos.rb
- scripts/fetch.ts
@mxcl do these pass your sniff test?
> changes needed to successfully build gcc

- .github/workflows/build.yml
- projects/deno.land/package.yml
- scripts/check-core-sizes.ts
> hard-code build exceptions

- projects/git-scm.org/package.yml
- proof of test: https://github.com/teaxyz/pantry.core/actions/runs/3936525240
- proof of fix: https://github.com/teaxyz/pantry.core/actions/runs/3936595089
fixes https://github.com/teaxyz/pantry.extra/issues/123
> fix git template directory

- projects/nodejs.org/package.yml
resolves #90
I'm not sure this is a great solution, but it works without segfaulting.
> Fix node linux build

- .github/workflows/index-data.yml
> Bugfix bottle ingest

- .github/workflows/index-data.yml
- .vscode/settings.json
- deno.jsonc
- scripts/index-packages.ts
> simplify index-packages

- .github/workflows/bottle.yml
- .github/workflows/build.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/complain.yml
- .github/workflows/new-version.yml
I think I forgot to do the actual thing.
> make branches actually parallel

- .github/workflows/bottle.yml
- .github/workflows/build.yml
- .github/workflows/cd.yml
- .github/workflows/index-data.yml
- scripts/get-platform.ts
resolves https://github.com/teaxyz/pantry.core/issues/187
> use actions/cache to reduce deno.land 500s

- .github/actions/apple-signing/action.yml
- .github/workflows/bottle.yml
ref https://github.com/teaxyz/cli/issues/376
> extract signing action

- projects/freetype.org/package.yml
help ensure no PIC/PIE issues.
> +test(freetype)

- .github/workflows/build.yml
- projects/ruby-lang.org/package.yml
> fix(ruby/rubygems)

- .github/actions/bottle/action.yml
- .github/actions/setup-brewkit/action.yml
- .github/actions/upload/action.yml
- .github/actions/upload/upload.ts
- .github/scripts/utils/gha.ts
- .github/workflows/bottle.yml
- .github/workflows/complain.yml
Ugh, took enough attempts.
Proof of end-to-end success: https://github.com/teaxyz/pantry.core/actions/runs/4269029158/jobs/7431930530
> Fix bottle.yml

- projects/harfbuzz.org/package.yml
> fix(harfbuzz)

- projects/nodejs.org/package.yml
fixes https://github.com/teaxyz/pantry.core/issues/465
fixes https://github.com/teaxyz/pantry.core/issues/184
> fix(nodejs)

- .github/actions/setup-brewkit/action.yml
- .github/workflows/build.yml
- tea.yaml
also hack to get tests working again
> restore brewkit to ^0.7.1

- projects/gnu.org/readline/fixture.c
- projects/gnu.org/readline/package.yml
- projects/invisible-island.net/ncurses/package.yml
- projects/python.org/package.yml
> mk ncurses install its headers namespaced and not

- projects/python.org/package.yml
python3.7-config is a symlink
resolves https://github.com/teaxyz/pantry.extra/issues/656
resolves #560
resolves #559 
resolves #558 
resolves #557
proof of success: https://github.com/teaxyz/pantry.core/actions/runs/4410951088
> fix(python~3.7)
